/**Even Fibonacci numbers
Problem 2
Published on Friday, 19th October 2001, 06:00 pm; Solved by 452550; Difficulty rating: 5%
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum
*/


using System;
class MainClass {
  public static void Main (string[] args) {
    int limit = 4000000;
    
    int result = evenFibonnaciSum(limit);
    
    Console.WriteLine (result);
  }
  
  public static int evenFibonnaciSum(int roof){
  		int sum = 0;
  	
    	int j = 1;
    	int k = 0;
    	for(int i = 0; i< roof; i++){
    		int temp = j + k;
    		
    		if(temp >= roof){
    			break;
    		}
    		
    		k = j;
    		j = temp;
    		
    		//Console.WriteLine(j +"  "+  k);
    		if(j % 2 == 0){
    			sum = sum + j;
    			//Console.WriteLine("          "+ sum);
    		}
    	}
    	return sum;
    }
}
      
