/**Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/


using System;

class MainClass {
	static bool inProgress = true;
	
	public static void Main (string[] args) {
		int i = 10000;

    	while(inProgress){
    		nextTriangleNumber(i);
    		i++;
    	}
  	}
  
	public static void nextTriangleNumber(int n){
	  	int sum = (int)(n*(n+1)*0.5);
	  	
	   	int total = 0;
	  	for(int i = 1; i*i <= sum; i++){
	  		if((sum % i) == 0){
	  			total = total + 2;
	  		}
	  	}
	
	  	if((sum >= 720720) && (total > 500)){
	  		Console.WriteLine(n +"\t"+ sum +"\t"+ total);
	  		inProgress = false;
	  	}
	}
  
}
